{
 "title": "Trickster",
 "description": "Dashboard for Trickster delta cache for TSDBs",
 "time": { "from": "now-3h", "to": "now-1m" },
 "templating": {
  "list": [
   { "name": "prometheus_label_name", "query": "${VAR_PROMETHEUS_LABEL_NAME}" },
   { "name": "prometheus_label_value", "query": "${VAR_PROMETHEUS_LABEL_VALUE}" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(process_start_time_seconds{app=\"trickster\"}, instance)"
    }
   },
   {
    "name": "aggregation_interval",
    "label": "Aggregation interval",
    "query": "1m,2m,3m,5m,10m,15m,30m,1h,6h,1d"
   },
   {
    "name": "origin_name",
    "label": "origin_name",
    "query": {
     "query": "label_values(trickster_proxy_requests_total{app=\"trickster\"}, origin_name)"
    }
   },
   {
    "name": "origin_type",
    "label": "origin_type",
    "query": {
     "query": "label_values(trickster_proxy_requests_total{app=\"trickster\"}, origin_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"https://github.com/trickstercache/trickster/tree/main/docs\" target=\"_blank\"><img src=\"https://i.imgur.com/uodNnPR.png\", width=\"200\", height=\"200\", style=\"position:relative;left:10%\"></img></a>"
   }
  },
  {
   "title": "Cache hit/miss",
   "type": "grafana-piechart-panel",
   "description": "Shows percentage of query cache hit or miss of Trickster. \nFor more info about cache success see graph info on the right.",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(trickster_proxy_points_total{app=\"trickster\", instance=~\"$instance\", origin_name=~\"$origin_name\", origin_type=~\"$origin_type\"}[$aggregation_interval])) by (cache_status)",
     "legendFormat": "{{ cache_status }}"
    }
   ]
  },
  {
   "title": "Percentage of cache hit",
   "type": "graph",
   "description": "Shows percentage and count of queried points found of not in Trickster cache.\n\n- cached = found in cache\n- uncached = not found in cache\n\n**The more cached the better.**",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(trickster_proxy_points_total{app=\"trickster\", instance=~\"$instance\", origin_name=~\"$origin_name\", origin_type=~\"$origin_type\"}[$aggregation_interval])) by (cache_status)",
     "legendFormat": "{{ cache_status }}"
    }
   ]
  },
  {
   "title": "# of Instances",
   "type": "stat",
   "description": "How many instances are running",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(process_start_time_seconds{app=\"trickster\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Query cache hit type",
   "type": "grafana-piechart-panel",
   "description": "Shows percentage of query cache hit types of Trickster. \nFor more info about cache hit types see graph info on the right.",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(trickster_proxy_requests_total{app=\"trickster\", instance=~\"$instance\", origin_name=~\"$origin_name\", origin_type=~\"$origin_type\"}[$aggregation_interval])) by (cache_status)",
     "legendFormat": "{{ cache_status }}"
    }
   ]
  },
  {
   "title": "Percentage of query cache hit types",
   "type": "graph",
   "description": "Shows percentage and count of query cache hit types. Those are:\n\n- rmiss = query range miss\n- kmiss = key not found in cache \n- phit = partial hit\n- hit = found all data in cache\n- purge = i'm not sure :) (probably cache flush)",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(trickster_proxy_requests_total{app=\"trickster\", instance=~\"$instance\", origin_name=~\"$origin_name\", origin_type=~\"$origin_type\"}[$aggregation_interval])) by (cache_status)",
     "legendFormat": "{{ cache_status }}"
    }
   ]
  },
  {
   "title": "# of served points",
   "type": "stat",
   "description": "Total count of points served",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(trickster_proxy_points_total{app=\"trickster\", instance=~\"$instance\", origin_name=~\"$origin_name\", origin_type=~\"$origin_type\"}[$aggregation_interval]))"
    }
   ]
  },
  {
   "title": "Total requests by instance",
   "type": "graph",
   "description": "Total count of requests aggregated by instance.\nShows how are the requests balanced.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(trickster_proxy_requests_total{app=\"trickster\", instance=~\"$instance\", origin_name=~\"$origin_name\", origin_type=~\"$origin_type\"}[$aggregation_interval])) by (instance)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(increase(trickster_proxy_requests_total{app=\"trickster\", instance=~\"$instance\", origin_name=~\"$origin_name\", origin_type=~\"$origin_type\"}[$aggregation_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Proxy request duration",
   "type": "heatmap",
   "description": "Shows how long the requests took to be served as histogram using quantiles. This means that x% was served faster than the value of the metric.\nThat means:\n- 50%: shows time before 50% of requests was served\n- 90%: shows time before 90% of requests was served\n- 99%: shows time before 99% of requests was served",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(trickster_proxy_request_duration_seconds_bucket{app=\"trickster\", instance=~\"$instance\", origin_name=~\"$origin_name\", origin_type=~\"$origin_type\"}[$aggregation_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total requests by http_status",
   "type": "graph",
   "description": "Shows total query count aggregated by type.\nThere are two types;\n- query: instant query resulting in data in given time\n- query_range: query for data in given time interval",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(trickster_proxy_requests_total{app=\"trickster\", instance=~\"$instance\", origin_name=~\"$origin_name\", origin_type=~\"$origin_type\"}[$aggregation_interval])) by (http_status)",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "sum(increase(trickster_proxy_requests_total{app=\"trickster\", instance=~\"$instance\", origin_name=~\"$origin_name\", origin_type=~\"$origin_type\"}[$aggregation_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Query calls per origin",
   "type": "table",
   "description": "This table shows query count by origin on which it was called. Those can differ depending on configuration of Trickster.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(trickster_proxy_requests_total{app=\"trickster\", instance=~\"$instance\", origin_name=~\"$origin_name\", origin_type=~\"$origin_type\"}[$aggregation_interval])) by (origin_name, origin_type)",
     "legendFormat": "{{ origin_type }} {{ origin_name }}"
    }
   ]
  },
  { "title": "Trickster performance data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "CPU usage/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=\"trickster\", instance=~\"$instance\"}[$aggregation_interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{container=\"trickster\", pod=~\"$instance\"}) by (instance)",
     "legendFormat": "Limit {{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=\"trickster\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{container=\"trickster\", pod=~\"$instance\"}) by (pod)",
     "legendFormat": "Limit {{ pod }}"
    }
   ]
  },
  { "title": "Prometheus performance data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Prometheus Query elapsed time",
   "type": "graph",
   "description": "This shows how long did it take  Prometheus to server requests.\nThis could be possibly lower time when using Trickster since the queries can be for smaller more recent time range.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(prometheus_engine_query_duration_seconds) by (instance, slice)",
     "legendFormat": "{{ slice }} {{ instance }}"
    }
   ]
  },
  {
   "title": "Prometheus Request count",
   "type": "graph",
   "description": "Shows total request count on Prometheus server.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prometheus_http_requests_total{$prometheus_label_name=~\"$prometheus_label_value\"}[$aggregation_interval])) by (instance, handler) > 0",
     "legendFormat": "{{ handler }} on {{ instance }}"
    }
   ]
  },
  {
   "title": "Prometheus request duration histogram",
   "type": "heatmap",
   "description": "Shows duration how long it takes to Prometheus to server requests aggregated by handlers",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_request_duration_seconds_bucket{$prometheus_label_name=~\"$prometheus_label_value\"}[$aggregation_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CPU usage/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{$prometheus_label_name=~\"$prometheus_label_value\"}[$aggregation_interval])",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{container=\"prometheus\"}) by (pod)",
     "legendFormat": "Limit {{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{$prometheus_label_name=~\"$prometheus_label_value\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{container=\"prometheus\"}) by (pod)",
     "legendFormat": "Limit {{pod}}"
    }
   ]
  }
 ]
}